// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ijcyeozyapwuneyjylij.supabase.co";
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqY3llb3p5YXB3dW5leWp5bGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjM4MjMsImV4cCI6MjA3MDQzOTgyM30.zL7RGKhsRrwcqk0IzUrH8EZiTNP4bXenJ4CgYQ8sFMo";

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("Missing Supabase env vars:", { SUPABASE_URL, SUPABASE_KEY: !!SUPABASE_KEY });
  throw new Error('Missing Supabase environment variables. Please check your .env or .env.local file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});